language: php
php:
  - '7.1'
  - hhvm-3.20
  - hhvm-nightly

sudo: required
dist: trusty
group: edge

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - COMPOSER_ALLOW_XDEBUG=0

notifications:
  email: false

install:
  - composer install --prefer-dist --optimize-autoloader

script: vendor/bin/phpunit
